# -*- conf -*-

font=FiraCode:size=12

[scrollback]
lines=10000

[cursor]
# color = <inverse foreground/background>
color=ffffff ff1493
blink=yes
blink-rate=500

[colors]
alpha=0.7
background=000000
foreground=ff1493

## Nord palette: Normal/regular colors (color palette 0-7)
regular0=4c566a  # black
regular1=bf616a  # red
regular2=a3be8c  # green
regular3=ebcb8b  # yellow
regular4=5e81ac  # blue
regular5=b48ead  # magenta
regular6=88c0d0  # cyan
regular7=d8dee9  # white
## Bright colors (color palette 8-15)
bright0=4c566a   # bright black
bright1=bf616a   # bright red
bright2=a3be8c   # bright green
bright3=ebcb8b   # bright yellow
bright4=5e81ac   # bright blue
bright5=b48ead   # bright magenta
bright6=88c0d0   # bright cyan
bright7=d8dee9   # bright white

## dimmed colors (see foot.ini(5) man page)
# dim0=<not set>
# ...
# dim7=<not-set>

## The remaining 256-color palette
# 16 = <256-color palette #16>
# ...
# 255 = <256-color palette #255>

## Misc colors
# selection-foreground=<inverse foreground/background>
# selection-background=<inverse foreground/background>
# jump-labels=<regular0> <regular3>          # black-on-yellow
# scrollback-indicator=<regular0> <bright4>  # black-on-bright-blue
# search-box-no-match=<regular0> <regular1>  # black-on-red
# search-box-match=<regular0> <regular3>     # black-on-yellow
# urls=<regular3>

[csd]
color=4c566a
hide-when-maximized=yes

[key-bindings]
clipboard-copy=Control+c XF86Copy
clipboard-paste=Control+v XF86Paste
font-increase=Control+plus Control+equal Control+KP_Add
font-decrease=Control+minus Control+KP_Subtract
font-reset=Control+0 Control+KP_0
spawn-terminal=Control+Shift+t
show-urls-launch=Control+Shift+o