#!/bin/bash

## Run eww daemon if not running already
if [[ -z $(eww active-windows | grep 'dashboard') ]]; then
  eww open dashboard && eww update mdashrev=true
else
  eww update mdashrev=false 
  (sleep 0.3 && eww close dashboard) &
fi
