#!/bin/bash

printJson() {
	vol=$(pactl get-source-volume @DEFAULT_SOURCE@ | awk '{print $5}' | tr -d "%")
	mute=$(pactl get-source-mute @DEFAULT_SOURCE@ | awk '{print $2}')

	if [[ "$mute" == "yes" ]]; then
		icon="󰍭"
		vol=0
	else
		icon="󰍬"
	fi

	# Output proper JSON
	echo "{\"value\": $vol, \"icon\": \"$icon\"}"
}

# Emit once on start
printJson

# Watch for sink change events
while true; do
	printJson
	sleep 1
done
