#!/bin/bash

## Open Applications
closeDash() {
  eww update mdashrev=false && eww close dashboard &
}

if [[ "$1" == "--br" ]]; then
	closeDash && brave &

elif [[ "$1" == "--of" ]]; then
	closeDash && onlyoffice-desktopeditors &

elif [[ "$1" == "--dc" ]]; then
	closeDash && discord &

elif [[ "$1" == "--cd" ]]; then
	closeDash && code &

elif [[ "$1" == "--ob" ]]; then
	closeDash && obsidian &

elif [[ "$1" == "--gde" ]]; then
	closeDash && godot &

elif [[ "$1" == "--fm" ]]; then
	closeDash && nautilus &

fi
