#Bashtop Everblush theme
#by RellotScrewdriver

# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#FFFFFF", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#141b1e"

# Main text color
theme[main_fg]="#dadada"

# Title color for boxes
theme[title]="#8ccf7e"

# Higlight color for keyboard shortcuts
theme[hi_fg]="#dadada"

# Background color of selected item in processes box
theme[selected_bg]="#e5c76b" 

# Foreground color of selected item in processes box
theme[selected_fg]="#232a2d"

# Color of inactive/disabled text
theme[inactive_fg]="#30"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#e57474"

# Cpu box outline color
theme[cpu_box]="#8cc7fe"

# Memory/disks box outline color
theme[mem_box]="#8cc7fe"

# Net up/down box outline color
theme[net_box]="#8cc7fe"

# Processes box outline color
theme[proc_box]="#8cc7fe"

# Box divider line and small boxes line color
theme[div_line]="#8cc7fe"

# Temperature graph colors
theme[temp_start]="#67b0e8"
theme[temp_end]="#e57474"

# CPU graph colors
theme[cpu_start]="#67b0e8"
theme[cpu_end]="#e57474"

# Mem/Disk free meter
theme[free_start]="#67b0e8"
theme[free_end]="#e57474"

# Mem/Disk cached meter
theme[cached_start]="#67b0e8"
theme[cached_end]="#e57474"

# Mem/Disk available meter
theme[available_start]="#67b0e8"
theme[available_end]="#e57474

# Mem/Disk used meter
theme[used_start]="#67b0e8"
theme[used_end]="#e57474"

# Download graph colors
theme[download_start]="#67b0e8"
theme[download_end]="#e57474"

# Upload graph colors
theme[upload_start]="#67b0e8"
theme[upload_end]="#e57474"
