#Bashtop ReSynthwave theme
#by RellotScrewdriver

# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#FFFFFF", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#000000"

# Main text color
theme[main_fg]="#00FFFF"

# Title color for boxes
theme[title]="#ff0ff"

# Higlight color for keyboard shortcuts
theme[hi_fg]="#ff00ff"

# Background color of selected item in processes box
theme[selected_bg]="#ff1493" 

# Foreground color of selected item in processes box
theme[selected_fg]="#000000"

# Color of inactive/disabled text
theme[inactive_fg]="#30"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#ff1493"

# Cpu box outline color
theme[cpu_box]="#ff1493"

# Memory/disks box outline color
theme[mem_box]="#ff1493"

# Net up/down box outline color
theme[net_box]="#ff1493"

# Processes box outline color
theme[proc_box]="#ff00ff"

# Box divider line and small boxes line color
theme[div_line]="#ff1493"

# Temperature graph colors
theme[temp_start]="#FF1493""
theme[temp_mid]="#FF1493"
theme[temp_end]="#FF1493"

# CPU graph colors
theme[cpu_start]="#FF1493"
theme[cpu_mid]="#FF1493"
theme[cpu_end]="#FF1493"

# Mem/Disk free meter
theme[free_start]="#FF1493"
theme[free_mid]="#FF1493"
theme[free_end]="#FF1493"

# Mem/Disk cached meter
theme[cached_start]="#FF1493"
theme[cached_mid]="#FF1493"
theme[cached_end]="#FF1493"

# Mem/Disk available meter
theme[available_start]="#FF1493"
theme[available_mid]="#FF1493"
theme[available_end]="#FF1493

# Mem/Disk used meter
theme[used_start]="#FF1493"
theme[used_mid]="#FF1493"
theme[used_end]="#FF1493"

# Download graph colors
theme[download_start]="#FF1493"
theme[download_mid]="#FF1493"
theme[download_end]="#FF1493"

# Upload graph colors
theme[upload_start]="#FF1493"
theme[upload_mid]="#FF1493"
theme[upload_end]="#FF1493"
