#!/bin/bash

## Open Applications
close_dash() {
  eww update mdashrev=false && eww close dashboard &
}

if [[ "$1" == "--br" ]]; then
	close_dash && brave &

elif [[ "$1" == "--of" ]]; then
	close_dash && onlyoffice-desktopeditors &

elif [[ "$1" == "--dc" ]]; then
	close_dash && discord &

elif [[ "$1" == "--cd" ]]; then
	close_dash && code &

elif [[ "$1" == "--ob" ]]; then
	close_dash && obsidian &

elif [[ "$1" == "--gde" ]]; then
	close_dash && godot &

elif [[ "$1" == "--fm" ]]; then
	close_dash && nautilus &

fi
