#!/bin/bash

printJson() {
	vol=$(pamixer --get-volume)
	mute=$(pamixer --get-mute)

	if [ "$mute" = true ]; then
		icon=""
		vol=0
	else
		if [ "$vol" -le 33 ]; then
			icon=""
		elif [ "$vol" -le 66 ]; then
			icon=""
    elif [ "$vol" -ge 100 ]; then
      setLock=$(pamixer --set-volume 100 && pamixer --get-volume)
      vol=$setLock
      icon=""
		else
			icon=""
		fi
	fi

	# Output proper JSON
  printf '{"icon":"%s","value":"%s"}\n' "$icon" "$vol%"
}

# Emit once on start
printJson

# Watch for sink change events
pactl subscribe | stdbuf -oL grep --line-buffered "Event 'change' on sink" | while read -r _; do
	printJson
done


