#!/bin/bash

getIcon() {
	upowerOutput=$(upower -i $(upower -e | grep 'BAT'))
	state=$(echo "$upowerOutput" | grep "state" | awk '{print $2}')
	percent=$(echo "$upowerOutput" | grep "percentage" | awk '{print $2}' | sed 's/%//')

	if [[ "$state" == "charging" || "$state" == "fully-charged" ]]; then
		if ((percent > 80)); then
      echo "󰉁"
		else
			echo ""
		fi
	else
		if ((percent > 90)); then
			echo ""
		elif ((percent > 70)); then
			echo ""
		elif ((percent > 40)); then
			echo ""
		elif ((percent > 10)); then
			echo ""
    else
			echo ""
		fi
	fi
}

getIcon # Output current state immediately

upower --monitor | while read -r line; do
	getIcon # Output on every change event
done
