#!/bin/bash

while true; do

	# CPU usage (% whole number)
	usage=$(top -bn1 | awk '/Cpu\(s\):/ {printf "%d", 100 - $8}')

	# Memory usage in form "used / total GB"
	mem=$(printf "%.0f\n" $(free -m | grep Mem | awk '{print ($3/$2)*100}'))

  	# CPU fan in number
  	fan=$(sensors | grep "cpu_fan" | awk '{print $2}')

	# Output JSON
	echo "{\"cpu_fan\": \"${fan}\", \"cpu_usage\": ${usage}, \"meminfo\": \"${mem}\"}"

	sleep 2
done
