#!/bin/bash

# 1. get temperature

## a. split response
## Core 0:       +143.6°F  (high = +186.8°F, crit = +212.0°F)
getCpuTemps(){
degree="°C"
temperatureValues=(40 50 60 70 80 90 100 110)
temperatureIcons=(       ☢)

IFS=')' read -ra core_temp_arr <<< $(sensors | grep -m 14 Core  | awk '{print substr($3, 2, length($3) - 5)}') #echo "${core_temp_arr[0]}"


## b. find cpu usage
totalcputemp=0.0
index=0
for i in "${core_temp_arr[@]}"; do :
    temp=$(echo $i | sed -n 's/°C.*//; s/.*[+-]//; p; q')
    let index++
    totalcputemp=$(echo "$totalcputemp + $temp" | bc)
done
avgCpuTemp=$(echo "scale=2; $totalcputemp / $index" | bc)

v=$(echo "$avgCpuTemp" | tr -cd '[:digit:]')
let v1=$v/100

if [ $v1 -lt 40 ];
then
  tmpEcho="${temperatureIcons[0]}"
else
  for (( i=1; i<=7; i++ ))
  do 
      if [ $v1 -ge ${temperatureValues[$i-1]} -a $v1 -lt ${temperatureValues[$i]} ];
      then
        tmpEcho="${temperatureIcons[$i]}"
      fi
  done
fi
}

getCpuTemps

while true; do
  getCpuTemps

  echo "{\"tempIcon\": \"${tmpEcho}\", \"tempNo\": "${v1}.0" }"

  sleep 2
done
