#!/bin/sh

staticWS="[1, 2, 3, 4, 5, 6]"

icons='{
    "1": "I",
    "2": "II",
    "3": "III",
    "4": "IV",
    "5": "V",
    "6": "VI"
}'

printWorkspaces() {
    swaymsg -t get_workspaces -r | jq -c --argjson static "$staticWS" --argjson icons "$icons" '
        # Store current sway workspaces
        . as $current_ws |
        
        # Iterate over the static list
        $static | map(
            . as $id |
            # Find matching workspace
            ($current_ws | map(select(.num == $id)) | .[0]) as $match |
            
            {
                id: $id,
                # Lookup icon; default to the ID number if no icon is defined
                icon: ($icons[$id | tostring] // $id), 
                status: (
                    if $match == null then 
                        "empty"
                    elif $match.focused then 
                        "focused"
                    elif $match.urgent then 
                        "urgent"
                    else 
                        "occupied" 
                    end
                )
            }
        )
    '
}

# Initial print
printWorkspaces

# Subscribe to changes
swaymsg -t subscribe -m '["workspace"]' | while read -r _; do
    printWorkspaces
done
