gui:
  theme:
    lightTheme: false 
    activeBorderColor:
      - "#76b0e8" # Green
      - bold
    inactiveBorderColor:
      - "#dadada"
    optionsTextColor:
      - "#e5c76b"
    selectedLineBgColor:
      - "#6cbfbf"
    selectedRangeBgColor:
      - "#6cbfbf"
    cherryPickedCommitBgColor:
      - "#c47fd5" 
    cherryPickedCommitFgColor:
      - "#dadada"
    unstagedChangesColor:
      - "#e57474"
